name: demoprueba
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0 # 🎵 AGREGADO: La librería para reproducir tu música

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 🎵 REGISTRO DE TUS TEMAS DE MVC2
  assets:
    - assets/audio/mvc2_carnival.mp3
    - assets/audio/mvc2_factory.mp3
    - assets/audio/mvc2_swamp.mp3